# .goreleaser.yaml
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0 # Static binaries are best for Ubuntu/Linux
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go # Path to your Cobra entry point
    binary: go-crud-app-cobra

archives:
  - format: tar.gz
    # use zip for windows
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'